---
jobs:
- name: fail-job
  plan:
  - task: fail
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/rootfs
      run:
        path: sh
        args:
        - -c
        - |
          echo "Triggering an exit error"
          exit 1 
